type PlayerData = {
  bot_identifier: string,
  language: string,
  name: string,
  email: string,
  code: string,
  avatar_b64: string | null,
  creation_datetime: string,
  built: boolean,
  image_identifier: string,
  dead: boolean,
  position_x: number,
  position_y: number,
  fuel: number,
  health: number,
  bullets: number,
  shield_mounted: boolean,
  victories: number,
}