type TurnData = {
  _id: string,
  turn_identifier: string,
  timestamp: string,
  session_identifier: string,
  bot_identifier: string,
  turn_number: number,
  origin_position_x: number,
  origin_position_y: number,
  origin_fuel: number,
  origin_health: number,
  origin_bullets: number,
  origin_victories: number,
  origin_shield_enabled: boolean,
  final_position_x: number,
  final_position_y: number,
  final_fuel: number,
  final_health: number,
  final_bullets: number,
  final_victories: number,
  final_shield_enabled: boolean,
  sent_payload: string,
  received_response: string,
  action: string,
  dead: boolean,
  collision: boolean,
  collision_to: string,
  hit: boolean,
  hit_to: string | null,
  target_reached: boolean,
  target_abs_coordinates: string,
  wrong_response: boolean,
  notes: string,
};