const gameData = 
  [
    {
        "turn_identifier": "d2cb535f-1041-4038-b45b-cb5973cde55c",
        "timestamp": "2023-08-21 17:19:56.960687",
        "session_identifier": "5a1d2e31-5173-4649-a0b2-9e85fa526860",
        "bot_identifier": "bot_A",
        "turn_number": 1,
        "origin_position_x": 8,
        "origin_position_y": 9,
        "origin_fuel": 100,
        "origin_health": 50,
        "origin_bullets": 4,
        "origin_victories": 0,
        "origin_shield_enabled": false,
        "final_position_x": 8,
        "final_position_y": 7,
        "final_fuel": 0,
        "final_health": 30,
        "final_bullets": 3,
        "final_victories": 0,
        "final_shield_enabled": false,
        "sent_payload": "Payload for bot_A",
        "received_response": "M0910",
        "action": "M",
        "dead": false,
        "collision": false,
        "collision_to": "",
        "target_reached": false,
        "wrong_response": false,
        "notes": ""
    },
    {
        "turn_identifier": "f6e7f07e-9062-475c-a9f3-eacc7a2e482e",
        "timestamp": "2023-08-21 17:19:56.960802",
        "session_identifier": "73a2fc15-a684-4e0a-972e-44ffdfcff8df",
        "bot_identifier": "bot_B",
        "turn_number": 1,
        "origin_position_x": 4,
        "origin_position_y": 6,
        "origin_fuel": 100,
        "origin_health": 40,
        "origin_bullets": 2,
        "origin_victories": 0,
        "origin_shield_enabled": false,
        "final_position_x": 6,
        "final_position_y": 6,
        "final_fuel": 90,
        "final_health": 50,
        "final_bullets": 2,
        "final_victories": 0,
        "final_shield_enabled": false,
        "sent_payload": "Payload for bot_B",
        "received_response": "M0506",
        "action": "M",
        "dead": false,
        "collision": false,
        "collision_to": "",
        "target_reached": false,
        "wrong_response": false,
        "notes": ""
    },
    {
      "turn_identifier": "f6e7f07e-9062-475c-a9f3-eacc7a2e482e",
      "timestamp": "2023-08-21 17:19:56.960802",
      "session_identifier": "73a2fc15-a684-4e0a-972e-44ffdfcff8df",
      "bot_identifier": "bot_C",
      "turn_number": 1,
      "origin_position_x": 2,
      "origin_position_y": 3,
      "origin_fuel": 100,
      "origin_health": 40,
      "origin_bullets": 2,
      "origin_victories": 0,
      "origin_shield_enabled": false,
      "final_position_x": 2,
      "final_position_y": 3,
      "final_fuel": 90,
      "final_health": 50,
      "final_bullets": 2,
      "final_victories": 0,
      "final_shield_enabled": false,
      "sent_payload": "Payload for bot_C",
      "received_response": "M0506",
      "action": "S",
      "dead": false,
      "collision": false,
      "collision_to": "",
      "target_reached": false,
      "wrong_response": false,
      "notes": ""
    },
    {
      "turn_identifier": "f6e7f07e-9062-475c-a9f3-eacc7a2e482e",
      "timestamp": "2023-08-21 17:19:56.960802",
      "session_identifier": "73a2fc15-a684-4e0a-972e-44ffdfcff8df",
      "bot_identifier": "bot_C",
      "turn_number": 2,
      "origin_position_x": 2,
      "origin_position_y": 3,
      "origin_fuel": 100,
      "origin_health": 40,
      "origin_bullets": 2,
      "origin_victories": 0,
      "origin_shield_enabled": false,
      "final_position_x": 3,
      "final_position_y": 4,
      "final_fuel": 90,
      "final_health": 50,
      "final_bullets": 2,
      "final_victories": 0,
      "final_shield_enabled": false,
      "sent_payload": "Payload for bot_C",
      "received_response": "M0506",
      "action": "M",
      "dead": false,
      "collision": false,
      "collision_to": "",
      "target_reached": false,
      "wrong_response": false,
      "notes": ""
    },
    {
      "turn_identifier": "f6e7f07e-9062-475c-a9f3-eacc7a2e482e",
      "timestamp": "2023-08-21 17:19:56.960802",
      "session_identifier": "73a2fc15-a684-4e0a-972e-44ffdfcff8df",
      "bot_identifier": "bot_B",
      "turn_number": 2,
      "origin_position_x": 6,
      "origin_position_y": 6,
      "origin_fuel": 100,
      "origin_health": 40,
      "origin_bullets": 2,
      "origin_victories": 0,
      "origin_shield_enabled": false,
      "final_position_x": 7,
      "final_position_y": 7,
      "final_fuel": 90,
      "final_health": 50,
      "final_bullets": 2,
      "final_victories": 0,
      "final_shield_enabled": false,
      "sent_payload": "Payload for bot_C",
      "received_response": "M0506",
      "action": "M",
      "dead": false,
      "collision": false,
      "collision_to": "",
      "target_reached": false,
      "wrong_response": false,
      "notes": ""
    },
    {
      "turn_identifier": "f6e7f07e-9062-475c-a9f3-eacc7a2e482e",
      "timestamp": "2023-08-21 17:19:56.960802",
      "session_identifier": "73a2fc15-a684-4e0a-972e-44ffdfcff8df",
      "bot_identifier": "bot_A",
      "turn_number": 3,
      "origin_position_x": 8,
      "origin_position_y": 7,
      "origin_fuel": 100,
      "origin_health": 40,
      "origin_bullets": 2,
      "origin_victories": 0,
      "origin_shield_enabled": false,
      "final_position_x": 8,
      "final_position_y": 7,
      "final_fuel": 90,
      "final_health": 50,
      "final_bullets": 2,
      "final_victories": 0,
      "final_shield_enabled": false,
      "sent_payload": "Payload for bot_C",
      "received_response": "M0506",
      "action": "R",
      "dead": false,
      "collision": false,
      "collision_to": "",
      "target_reached": false,
      "wrong_response": false,
      "notes": ""
    },
  ]

export default gameData;
